apiVersion: v1
kind: ReplicationController
metadata:
  name: test-backend
spec:
  replicas: 2
  selector:
    app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers: 
      - name: test
        image: hub.didiyun.com/utry/test-backend:latest
        ports:
        - containerPort: 18081
      imagePullSecrets:
      - name: didiyun