apiVersion: v1
kind: ReplicationController
metadata:
  name: test
spec:
  replicas: 2
  selector:
    app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers: 
      - name: test
        image: hub.didiyun.com/utry/test:latest
        ports:
        - containerPort: 18080
      imagePullSecrets:
      - name: didiyun